FROM node:12.2
RUN groupadd --gid 5000 nodeuser \
&& useradd --home-dir /home/nodeuser --create-home --uid 5000 \
--gid 5000 --shell /bin/sh --skel /dev/null nodeuser
ENV HOME=/home/app
RUN apt-get update && apt-get install htop
COPY package.json package-lock.json $HOME/node_docker/
WORKDIR $HOME/node_docker
RUN npm install --silent --progress=false
COPY . $HOME/node_docker
EXPOSE 8080
USER nodeuser
CMD [ "node", "server.js" ]
