FROM node:10-alpine

RUN mkdir -p /home/node/app/node_modules && chown -R 1100:node /home/node/app

WORKDIR /home/node/app

COPY package*.json ./

RUN npm install
USER 1100
COPY --chown=1100:node . .

EXPOSE 8080

CMD [ "node", "server.js" ]
