FROM node:12.2
RUN useradd --uid 1100 example --create-home
RUN apt-get update && apt-get install htop
COPY package.json package-lock.json /tmp/
WORKDIR /tmp/
RUN npm install --silent --progress=false
COPY . /tmp
EXPOSE 8080
RUN chown -R 1100 /tmp/*
RUN chown -R 1100 /tmp/server.js
USER 1100
CMD [ "node", "/tmp/server.js" ]
